import React from 'react';
import { GoogleGenAI } from "@google/genai";
import { Github, Check, Loader2 } from 'lucide-react';

interface AppIconsGeneratorProps {
  onBack: () => void;
  githubToken: string | null;
  onConnectGithub: () => void;
}

export default function AppIconsGenerator({ onBack, githubToken, onConnectGithub }: AppIconsGeneratorProps) {
  const [icons, setIcons] = React.useState<string[]>([]);
  const [loading, setLoading] = React.useState(false);
  const [uploading, setUploading] = React.useState<number | null>(null);
  const [uploaded, setUploaded] = React.useState<number[]>([]);

  const generateIcons = async () => {
    setLoading(true);
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              text: 'A set of professional app icons for a financial app named ZenFinance. Minimalist design, balanced zen stones (cairn) with a subtle currency symbol, sleek 3D render, dark mode aesthetic, deep indigo and emerald colors, high resolution, white background for easy cropping.',
            },
          ],
        },
      });

      const newIcons: string[] = [];
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          newIcons.push(`data:image/png;base64,${part.inlineData.data}`);
        }
      }
      setIcons(newIcons);
    } catch (error) {
      console.error('Error generating icons:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleUploadToGithub = async (index: number, base64Data: string) => {
    if (!githubToken) {
      onConnectGithub();
      return;
    }

    setUploading(index);
    try {
      // 1. Get user info
      const userRes = await fetch('https://api.github.com/user', {
        headers: { Authorization: `token ${githubToken}` }
      });
      const userData = await userRes.json();
      const username = userData.login;

      // 2. Create/Get repo named 'zen-finance-assets'
      const repoName = 'zen-finance-assets';
      const repoRes = await fetch(`https://api.github.com/repos/${username}/${repoName}`, {
        headers: { Authorization: `token ${githubToken}` }
      });

      if (repoRes.status === 404) {
        // Create repo
        await fetch('https://api.github.com/user/repos', {
          method: 'POST',
          headers: { 
            Authorization: `token ${githubToken}`,
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            name: repoName,
            description: 'Assets generated by ZenFinance App',
            private: false
          })
        });
      }

      // 3. Upload file
      const fileName = `icon-${Date.now()}.png`;
      const content = base64Data.split(',')[1]; // Remove data:image/png;base64,

      await fetch(`https://api.github.com/repos/${username}/${repoName}/contents/${fileName}`, {
        method: 'PUT',
        headers: { 
          Authorization: `token ${githubToken}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          message: `Add generated icon ${fileName}`,
          content: content
        })
      });

      setUploaded(prev => [...prev, index]);
    } catch (error) {
      console.error('Error uploading to GitHub:', error);
      alert('Ошибка при загрузке в GitHub. Проверьте права доступа токена.');
    } finally {
      setUploading(null);
    }
  };

  return (
    <div className="p-4 lg:p-8 min-h-screen text-white">
      <div className="max-w-4xl mx-auto">
        <button 
          onClick={onBack}
          className="mb-8 flex items-center gap-2 text-white/40 hover:text-white transition-colors"
        >
          ← Назад к дашборду
        </button>
        <h1 className="text-3xl font-bold mb-4">Генератор иконок ZenFinance</h1>
        <p className="text-white/60 mb-8">
          Я создам для вас набор профессиональных иконок, которые сочетают в себе спокойствие (Zen) и финансы.
        </p>

        <button
          onClick={generateIcons}
          disabled={loading}
          className="btn-primary px-8 py-4 text-lg mb-12 disabled:opacity-50"
        >
          {loading ? 'Создание иконок...' : 'Сгенерировать иконки'}
        </button>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {icons.map((src, i) => (
            <div key={i} className="glass-card p-4 flex flex-col items-center">
              <img src={src} alt={`Icon ${i}`} className="w-64 h-64 rounded-3xl shadow-2xl mb-4" referrerPolicy="no-referrer" />
              <p className="text-sm text-white/40 italic">Вариант {i + 1}</p>
              <div className="flex gap-4 mt-4">
                <a 
                  href={src} 
                  download={`zenfinance-icon-${i}.png`}
                  className="text-white/60 hover:text-white text-sm font-medium transition-colors"
                >
                  Скачать PNG
                </a>
                <button
                  onClick={() => handleUploadToGithub(i, src)}
                  disabled={uploading !== null || uploaded.includes(i)}
                  className={`flex items-center gap-2 text-sm font-medium transition-colors ${
                    uploaded.includes(i) ? 'text-emerald-400' : 'text-indigo-400 hover:text-indigo-300'
                  }`}
                >
                  {uploading === i ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : uploaded.includes(i) ? (
                    <Check className="w-4 h-4" />
                  ) : (
                    <Github className="w-4 h-4" />
                  )}
                  {uploaded.includes(i) ? 'Загружено' : 'В GitHub'}
                </button>
              </div>
            </div>
          ))}
        </div>

        {icons.length === 0 && !loading && (
          <div className="border-2 border-dashed border-white/10 rounded-3xl p-20 text-center text-white/20">
            Нажмите кнопку выше, чтобы начать
          </div>
        )}
      </div>
    </div>
  );
}
